<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAD-I-024" name="testCases.Matrixflow" tests="9" failures="8" timestamp="4 Jan 2019 13:40:31 GMT" time="36.246" errors="0">
  <testcase name="assigncase" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- assigncase -->
  <testcase name="Login" time="20.793" classname="testCases.Matrixflow"/>
  <testcase name="aasignToDE" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- aasignToDE -->
  <testcase name="Report" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- Report -->
  <testcase name="publishCase" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- publishCase -->
  <testcase name="OperationtmAssign" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- OperationtmAssign -->
  <testcase name="caseregistration" time="15.453" classname="testCases.Matrixflow">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for presence of element located by: By.id: ok (tried for 10 second(s) with 500 milliseconds interval)">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: ok (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at pages.Caseregistration.caseRegistration(Caseregistration.java:60)
	at testCases.Matrixflow.caseregistration(Matrixflow.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: ok
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'KAD-I-024', ip: '192.168.2.93', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	... 26 more
]]>
    </failure>
  </testcase> <!-- caseregistration -->
  <testcase name="Operationtm" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- Operationtm -->
  <testcase name="dataentry" time="0.000" classname="testCases.Matrixflow">
    <failure type="java.lang.RuntimeException" message="javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:99)
	at testCases.Matrixflow.afterSuite(Matrixflow.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.MessagingException: IOException while sending message;
  nested exception is:
	java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1167)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at environment.SendAttachmentInEmail.sendhtmlemail(SendAttachmentInEmail.java:92)
	... 19 more
Caused by: java.io.FileNotFoundException: D:\gopi\git\matextesting\Reports\matex.html (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at javax.activation.FileDataSource.getInputStream(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:865)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:462)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:103)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1485)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1773)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	... 22 more
]]>
    </failure>
  </testcase> <!-- dataentry -->
</testsuite> <!-- testCases.Matrixflow -->
